### ISSUE TITLE
Chapter 4 is missing some part of code

### ISSUE THREAD

**Issue by anitalakhadze** [PacktPublishing/Learning-Spring-Boot-3.0-Third-Edition#4]
Chapter 4 of the book (third edition) is missing the part where YouTube interface should be configured as an HTTP service and as a result, starting the application returns an error: "HomeController required a bean of type 'YouTube' that could not be found." The snippet that is missing is referenced below: 

https://github.com/PacktPublishing/Learning-Spring-Boot-3.0-Third-Edition/blob/16bcb8ce9528fd8144cc3ea1c7338523c8589a22/ch4-oauth/src/main/java/com/springbootlearning/learningspringboot3/YouTubeConfig.java#L32C1-L42C4

**Comment by gregturn** [comment]
One potential solution is making the `YouTube` interface `public`. Tell me if that does the trick. If so, we can add it to book's errata.

**Comment by gregturn** [comment]
Actually, I'm not sure what's happening. I just ran that application from a fresh repository clone, with my own clientId and clietnSecret plugged in, and it worked just fine. So making the interface public has nothing to do with your issue.

**Comment by gregturn** [comment]
Are you saying that the manuscript itself doesn't mention that YouTube service?

**Comment by anitalakhadze** [comment]
Hello Greg, thank you for replying to my issue. 
Sorry for making the description unclear. Yes, I meant that the manuscript itself (at least, the edition I had) did not mention that service and it could only be found in the repository.

**Comment by gregturn** [comment]
Okay, I've alerted the editors at Packt to update the errata and mention this shortfall.

In the meantime, I'm hoping you have enjoyed the book!

Also, in case you didnt' know, I was cut from the Spring team back in November amidst the Broadcom acquisition. I don't make Spring Boot-specific videos anymore. But if you're interested in tips on better learning how to be a pro coder, check out my latest wave of new content over at https://www.youtube.com/@ProCoderIO

**Comment by anitalakhadze** [comment]
Thank you, Greg. 

Indeed, I did enjoy the book very much and I also expressed my gratitude in a [linkedIn post](https://www.linkedin.com/posts/activity-7195036022966042624-U_iO?utm_source=share&utm_medium=member_desktop).

I am also a regular viewer of your content and once again, thank you for your efforts. It really makes a huge difference.
