### ISSUE TITLE
Deprecated Method on CH4

### ISSUE THREAD

**Issue by matheusromano** [PacktPublishing/Learning-Spring-Boot-3.0-Third-Edition#7]
@Bean
SecurityFilterChain configureSecurity(HttpSecurity http)
 throws Exception {
 http.authorizeHttpRequests() //
 .requestMatchers("/login").permitAll() //
 .requestMatchers("/", "/search").authenticated() //
 .requestMatchers(HttpMethod.GET, "/api/**")
 .authenticated() //
 .requestMatchers(HttpMethod.POST, "/new-video",
 "/api/**").hasRole("ADMIN") //
 .anyRequest().denyAll() //
 .and() //
 .formLogin() //
 .and() //
 .httpBasic();
 return http.build();
}

some methods of this security polices are deprecated, and i cant build my project with this code.

**Comment by matheusromano** [comment]
Found a solution. using this code:

@Bean
    SecurityFilterChain configureSecurity(HttpSecurity http) throws Exception {
        http
                .authorizeHttpRequests(authz -> authz
                        .requestMatchers("/login").permitAll()
                        .requestMatchers("/", "/search").authenticated()
                        .requestMatchers(HttpMethod.GET, "/api/**").authenticated()
                        .requestMatchers(HttpMethod.POST, "/new-video", "/api/**").hasRole("ADMIN")
                        .anyRequest().denyAll()
                )
                .formLogin(Customizer.withDefaults())
                .httpBasic(Customizer.withDefaults());

        return http.build();
    }

**Comment by gregturn** [comment]
I'm glad you found a solution.

It's important to be aware that this book was written against Spring Boot 3.0 and subsequently released December 2022. Check https://spring.io/projects/spring-boot#support and you'll see that OSS support for Spring Boot 3.0 ended November 2023.

I'm not saying that Spring Boot breaks you horribly. The opposite. Spring makes it quite easy to upgrade. Sometime you bump into deprecated APIs. So you either need to use the version that came with book, or you need to work through the API upgrades which are usually pretty well documented, either in the ref docs, their blog articles, or directly in the Javadocs of Spring.
